import './globals.css';
import { Analytics } from '@vercel/analytics/next';
import { site, absolute } from '@/data/site';
import { experiences } from '@/data/experience';

const TITLE = 'Milan Bomjan | QA Automation Engineer — Playwright, K6, CI/CD';
const DESCRIPTION =
  'QA Automation Engineer at Orion Tech Solutions, working remotely from Kathmandu with US teams. Playwright, API testing, performance testing (K6, JMeter) and CI/CD.';

/** @type {import("next").Metadata} */
export const metadata = {
  metadataBase: new URL(site.url),

  title: {
    default: TITLE,
    template: `%s | ${site.shortName}`,
  },
  description: DESCRIPTION,
  applicationName: `${site.name} Portfolio`,

  keywords: [
    'QA Automation Engineer',
    'Remote QA Engineer',
    'SDET',
    'Playwright Automation',
    'Cypress Testing',
    'API Testing',
    'Performance Testing',
    'K6 Load Testing',
    'JMeter Performance Testing',
    'Test Automation Framework',
    'CI/CD Testing',
    'JavaScript Test Automation',
    'Software Testing',
    'QA Engineer Nepal',
    'QA Automation Engineer Kathmandu',
    'Remote QA Engineer for US companies',
  ],

  authors: [{ name: site.name, url: site.url }],
  creator: site.name,
  publisher: site.name,
  category: 'technology',

  alternates: {
    canonical: '/',
  },

  // Phone numbers and emails are real links already — stop iOS from wrapping
  // arbitrary numbers (dates, versions) in tel: anchors.
  formatDetection: {
    telephone: false,
    address: false,
    email: false,
  },

  openGraph: {
    type: 'profile',
    firstName: 'Milan',
    lastName: 'Bomjan Tamang',
    username: 'MEELAN2001',
    title: TITLE,
    description: DESCRIPTION,
    url: site.url,
    siteName: `${site.name} — ${site.roleLong}`,
    locale: 'en_US',
    // og:image is generated by app/opengraph-image.jsx
  },

  twitter: {
    card: 'summary_large_image',
    title: TITLE,
    description: DESCRIPTION,
    // twitter:image is generated by app/twitter-image.jsx
  },

  robots: {
    index: true,
    follow: true,
    googleBot: {
      index: true,
      follow: true,
      noimageindex: false,
      'max-image-preview': 'large',
      'max-snippet': -1,
      'max-video-preview': -1,
    },
  },

  verification: {
    google: 'DyhkAT-goLeQnjNDUU-mLVxZPR1ajZAW2H7gJPmJEa0',
  },
};

export const viewport = {
  width: 'device-width',
  initialScale: 1,
  maximumScale: 5,
  themeColor: '#e85d04',
  // The design is light-only; declaring it stops browsers from auto-darkening.
  colorScheme: 'light',
};

const currentRole = experiences.find((e) => e.current);

/**
 * A connected @graph rather than a bare Person: search engines resolve the
 * @id references into one entity, which is what earns the knowledge-panel /
 * rich-result treatment. A lone Person node has far weaker signal.
 */
function buildJsonLd() {
  const personId = absolute('/#person');
  const websiteId = absolute('/#website');
  const employerId = `${site.employer.url}#organization`;

  return {
    '@context': 'https://schema.org',
    '@graph': [
      {
        '@type': 'Person',
        '@id': personId,
        name: site.name,
        givenName: 'Milan',
        familyName: 'Bomjan Tamang',
        jobTitle: currentRole?.role ?? site.role,
        description: DESCRIPTION,
        url: site.url,
        image: {
          '@type': 'ImageObject',
          '@id': absolute('/#profile-photo'),
          url: absolute('/profile.jpg'),
          width: 400,
          height: 490,
          caption: site.name,
        },
        email: `mailto:${site.email}`,
        telephone: site.phoneE164,
        address: {
          '@type': 'PostalAddress',
          addressLocality: site.base.city,
          addressCountry: site.base.countryCode,
        },
        homeLocation: {
          '@type': 'Place',
          name: `${site.base.city}, ${site.base.country}`,
          geo: {
            '@type': 'GeoCoordinates',
            latitude: site.base.latitude,
            longitude: site.base.longitude,
          },
        },
        worksFor: { '@id': employerId },
        hasOccupation: {
          '@type': 'Occupation',
          name: site.role,
          occupationalCategory: '15-1253.00', // O*NET: Software QA Analysts and Testers
          skills: site.expertise.join(', '),
          occupationLocation: {
            '@type': 'City',
            name: `${site.employer.city}, ${site.employer.region}`,
          },
        },
        alumniOf: {
          '@type': 'CollegeOrUniversity',
          name: site.education.school,
          url: site.education.url,
        },
        knowsAbout: site.expertise,
        knowsLanguage: [
          { '@type': 'Language', name: 'English' },
          { '@type': 'Language', name: 'Nepali' },
        ],
        sameAs: [site.socials.github, site.socials.linkedin, site.socials.facebook],
      },
      {
        '@type': 'Organization',
        '@id': employerId,
        name: site.employer.name,
        url: site.employer.url,
        address: {
          '@type': 'PostalAddress',
          addressLocality: site.employer.city,
          addressRegion: site.employer.regionCode,
          addressCountry: site.employer.countryCode,
        },
      },
      {
        '@type': 'WebSite',
        '@id': websiteId,
        url: site.url,
        name: `${site.name} — ${site.roleLong}`,
        description: DESCRIPTION,
        inLanguage: 'en',
        publisher: { '@id': personId },
      },
      {
        '@type': 'ProfilePage',
        '@id': absolute('/#webpage'),
        url: site.url,
        name: TITLE,
        description: DESCRIPTION,
        isPartOf: { '@id': websiteId },
        about: { '@id': personId },
        mainEntity: { '@id': personId },
        primaryImageOfPage: { '@id': absolute('/#profile-photo') },
        inLanguage: 'en',
      },
    ],
  };
}

export default function RootLayout({ children }) {
  return (
    <html lang="en" className="no-js" suppressHydrationWarning>
      <body>
        <script
          type="application/ld+json"
          // Structured data must ship in the HTML for crawlers that do not
          // execute JS, so it is inlined rather than loaded via next/script.
          dangerouslySetInnerHTML={{ __html: JSON.stringify(buildJsonLd()) }}
        />
        <script
          // Runs synchronously before first paint. Scroll-reveal animations
          // (see Reveal.jsx) render server-side with opacity:0, so if this
          // never fires — script blocked, JS disabled — .no-js's CSS
          // override (globals.css) keeps that content visible instead of
          // permanently hidden.
          dangerouslySetInnerHTML={{
            __html: "document.documentElement.classList.remove('no-js')",
          }}
        />
        {children}
        <Analytics />
      </body>
    </html>
  );
}
